Repository mizdra/scrapbox-userscript-icon-suggestion, pull requests merged in 2021-05, with the labels that each got.

#9 Fix typo
  README.md
Labels: documentation

#15 SuggestBox のテストを追加
  package.json
  src/App.tsx
  src/components/PopupMenu.tsx
  src/components/SuggestionBox.tsx
  src/lib/scrapbox.ts
  test/components/PopupMenu.test.tsx
  test/components/SuggestBox.test.tsx
  test/components/__snapshots__/SuggestBox.test.tsx.snap
  test/helpers/key.ts
  test/lib/scrapbox.test.ts
  yarn.lock
Labels: bug

#27 E2E テストの結果を Slack に通知するように
  .github/workflows/e2e-test.yml
  .github/workflows/nodejs.yml
Labels: MergeCat
